ph_admin/urls.py
from django.conf.urls import include, url
from urlmiddleware.conf import middleware, mpatterns
from ph_common_api import middleware_manager as ph_middleware_manager


from ph_admin import views

urlpatterns = [
       url('^register/user', views.UserCreationView.as_view(), name='user-creation' ),
       url('^register/customer', views.CustomerCreationView.as_view(),  name='customer-creation'),
       url('^register/honeycomb', views.HoneycombCustomerCreationView.as_view(),  name='honeycomb-customer-creation'),
       url('^sms-tool', views.SmsToolView.as_view(),  name='sms-tool'),
       url('^logout', views.LogoutView.as_view(),  name='logout'),
       url(r'hooks/queenfirmwares', views.QueenFirmwareUpdateView.as_view(), name='queen_firmware_update'),
       url(r'hooks/smsinbound', views.SMSInboundView.as_view(), name='sms_inboud_view'),
       url(r'hooks/payment/mvola', views.SMSInboundView.as_view(), name='payment-mvola')
]


middlewarepatterns = mpatterns('',
    middleware(r'^hooks/', ph_middleware_manager.DisableCSRFIfNotRequired),
)

powerhive/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.contrib.auth import middleware as django_auth_middleware#.AuthenticationMiddleware
from ph_admin import urls as ph_admin_urls
from ph_common_api import auth
from ph_common_api import middleware_manager
from urlmiddleware.conf import middleware, mpatterns
from ph_firmware_grid_api import firmware_middleware
from ph_mobile_payment_service import  urls as mpservice_urls
import django

from ph_model.admin import admin as ph_model_admin

urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^api/', include('ph_firmware_grid_api.urls')),
    url(r'^om/chart/', include('ph_om_chart_api.urls')),
    url(r'^om/', include('ph_om_grid_api.urls')),
    url(r'^ph_admin/', include(ph_admin_urls, namespace='ph_admin') ),
	url(r'^chaining/', include('smart_selects.urls')),
    url(r'^login/$', django.contrib.auth.views.login, kwargs={"template_name":"admin/login.html"},name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mmp/', include(mpservice_urls, namespace='ph_mobile_payment_service')),
    url(r'^$', django.views.generic.RedirectView.as_view(url='/admin/'))
]



middlewarepatterns = mpatterns('',
    middleware(r'^om/', auth.OMLoginRequiredMiddleware),
    middleware(r'^api/', django_auth_middleware.AuthenticationMiddleware),
    middleware(r'^om/', middleware_manager.RequestLoggingMiddleware),
    middleware(r'^api/', middleware_manager.RequestLoggingMiddleware),
    middleware(r'^api/', firmware_middleware.QueenContactServerMiddleware),
    middleware(r'^mmp/',middleware_manager.RequestLoggingMiddleware)
)

ph_admin/forms.py
from django import forms
import ph_model.models as ph_model
from ph_model.models import municipality

class CustomerCreationForm(forms.ModelForm):
    firstName = forms.CharField(label='First Name', max_length=100)
    lastName = forms.CharField(label='Last Name', max_length=100)
    phoneNumber = forms.CharField(label='Phone Number', max_length=100)
    email = forms.EmailField(label='Email')
    municipality = forms.ModelChoiceField(queryset=municipality.Municipality.objects.all())

    class Meta:
        model = ph_model.customer.Customer
        fields = ('firstName', 'lastName', 'email', 'phoneNumber', 'municipality')

class SmsToolForm(forms.Form):
    targetCsv = forms.FileField(label='Recipients CSV')
    message = forms.CharField(label='Message', max_length=160, widget=forms.TextInput(attrs={'size':160}))

    class Meta:
        fields = ('targetCsv', 'message')

ph_admin/views.py
""" set default encode to utf-8 to ameliorate unicode problems til we can upgrade to 3 """
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from django.contrib.auth import forms as django_forms
from django.contrib.auth.views import logout
import forms as ph_forms
from django.views.generic.edit import FormView
from ph_operation import customer_manager
from django.views.generic.base import View
from django import  http
from ph_operation import queen_firmware_manager
from ph_operation import sms_manager
from ph_util import email_util
import logging
import json
import csv

LOGGER = logging.getLogger(__name__)

class UserCreationView(FormView):
    """Django user admin view."""
    template_name = 'user_register.html'
    form_class = django_forms.UserCreationForm
    success_url = '/admin/auth/user/'

    def form_valid(self, form):
        form.save()
        return super(UserCreationView, self).form_valid(form)


class CustomerCreationView(FormView):
    """powerhive customer creation view."""
    template_name = 'customer_register.html'
    form_class = ph_forms.CustomerCreationForm
    success_url = '/admin/ph_model/customer/'

    def form_valid(self, form):
        # don't save to db here, let the customer class do it
        #form.save()
        # !!! TODO: fix the customer class account creation :/
        customer = form.instance
        customer_manager.CustomerManager.initialize_customer(customer)
        return super(CustomerCreationView, self).form_valid(form)


class HoneycombCustomerCreationView(View):
    """user creation handler for posts from honeycomb/angular"""
    def get(self, request):
        raise Exception('not supported.')

    def post(self, request):
        data = json.loads(request.body)
        form = ph_forms.CustomerCreationForm(data)
        if form.is_valid():
            customer = form.instance
            customer_manager.CustomerManager.initialize_customer(customer)
            return http.HttpResponse('success')
        else:
            return http.HttpResponse(form.errors.as_json())

class SmsToolView(FormView):
    """mass sms tool"""
    template_name = 'sms_tool.html'
    form_class = ph_forms.SmsToolForm
    success_url = '/ph_admin/sms-tool/success'

    def post(self, request, *args, **kwargs):
        form = ph_forms.SmsToolForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['targetCsv']
            message = request.POST['message']
            results = sms_manager.send_mass_sms(file, message)
            return http.HttpResponse(json.dumps(results), content_type='application/json')
        else:
            return http.HttpResponse(form.errors.as_json())

class QueenFirmwareUpdateView(View):
    """Sync queen firmwares."""
    def get(self, request):
        """Sync released queen firmwares to list of available firmwares,"""
        queen_firmware_manager.QueenFirmwareManager.sync_firmwares()
        return http.HttpResponse('Firmwares sync done!!!')

class LogoutView(View):
    """Logout"""
    def get(self, request):
        logout(request)
        return http.HttpResponse('Logout')



class SMSInboundView(View):
    """Process incoming sms."""
    def get(self, request):
        """Process get sms, if the notifier happended to send via get request"""
        raise Exception('Incoming message access via get not supported.')

    def post(self, request):
        """Process inbound message."""
        #TODO(estifanos): Process the actual sms message remove email notification not sure if is important.
        data = {"path": request.get_full_path(),
                "message": request.body,
                "requester": request.get_host()}
        #email_util.send_template_email("Incmoing SMS Message", 'hook_notification_template.html', data)
        sms_manager.CustomerSMSManager.fetch_incoming_sms_message()
        return http.HttpResponse('SMS Message processed')

ph_admin/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        {% get_static_prefix as STATIC_PREFIX %}
        {% block stylesheets %}
                <link rel="stylesheet" href="{{ STATIC_PREFIX }}/css/style.css" />
        {% endblock %}
    </head>
    <body>
            <div class="block">
                {% block content %}
                {% endblock %}
            </div>
    </body>
</html>

ph_admin/templates/base_email_template.html
<!DOCTYPE html>

<html>
    <head>
      <h2>Hi {% if ph_admins %} {{ph_admins}} {% else %} Admins {% endif %} ({{PH_SERVER}}) </h2>
    </head>
    <body>
            <div class="block">
                {% block content %}
                {% endblock %}
            </div>
    </body>

    <p>
    -----------------------------------------------------<br/>
       Powerhive Inc<br/>
       816 Bancroft Way<br/>
       Berkeley, CA 94710</p>
</html>

ph_admin/templates/cron_job_email_log_template.html
{% extends "base_email_template.html" %}

{% block content %}
<div> Cron triggered process summary</div><br/>
<table style="width:100%">
    <tr align="left">
        <th>Run Since </th>
        <th>Process</th>
        <th>Success</th>
        <th>Counts</th>

    </tr>
    {% for cron_job in cron_job_logs %}
    <tr style="{% if not cron_job.is_success %}color:red{% endif %}">
        <td>{{cron_job.run_since}}</td>
        <td>{{cron_job.code}}</td>
        <td>{{cron_job.is_success}}</td>
        <td>{{cron_job.counts}}</td>

    </tr>
    {% empty %}
    <li>No cron job log is found!</li>
    {% endfor %}
</table>
{% endblock %}

ph_admin/templates/customer_register.html
{% extends "base.html" %}

{% block content %}
<h2>Customer Registration</h2>
<form action="{% url 'ph_admin:customer-creation'%}" method="post">
    {% csrf_token %}
    <div class="customer_registeration">
        {{form.as_p}}
        <input type="submit" value="Register" class="'register-btn"/>
    </div>
</form>
{% endblock %}

ph_admin/templates/event_raised_template.html
{% extends "base_email_template.html" %}
{% load filters_or_tags %}
{% block content %}
<div> New Event raised</div><br/>
Event Type: {{eventType.itemType}}: {{eventType.eventNumber}}<br/>
Event Description: {{eventType.eventDescription}}<br/>
DeviceId: <a href="{% construct_event_url eventType.itemType event.itemId %}"> {{event.itemId}}</a><br/>
Event Details:
<ul>
    {% for eventDetail in eventDetails %}
     <li>{{eventDetail.itemName}} : {{eventDetail.itemValue}}</li>
     <br/>

    {% empty %}
    <li>No details!</li>
    {% endfor %}
</ul>

{% endblock %}

ph_admin/templates/first_solar_report.html
{% extends "base_email_template.html" %}

{% block content %}
<div> Please Find attached Report</div>
{% endblock %}

ph_admin/templates/hook_notification_template.html
{% extends "base_email_template.html" %}

{% block content %}
<div> New Incoming notification from {{requester}}</div><br/>
Processed at: {{path}}<br/>
Message<br/>:
{{message}}
{% endblock %}

ph_admin/templates/scratchcard_pin_list_template.html
{% extends "base_email_template.html" %}

{% block content %}
<div> Please Find attached scratchcard pins</div>
{% endblock %}

ph_admin/templates/sms_tool.html
{% extends "base.html" %}

{% block content %}
<h2>Mass SMS Tool</h2>
<form enctype="multipart/form-data" action="{% url 'ph_admin:sms-tool'%}" method="post">
    {% csrf_token %}
    <div class="">
        {{form.as_p}}
        <input type="submit" value="Send SMS Broadcast" class="'register-btn"/>
    </div>
</form>
{% endblock %}

ph_admin/templates/user_register.html
{% extends "base.html" %}

{% block content %}
<h2>O&M Registration</h2>
<form action="{% url 'ph_admin:user-creation'%}" method="post">
    {% csrf_token %}
    <div class="user_registeration">
        {{form.as_p}}
        <input type="submit" value="Register" class="'register-btn"/>
    </div>
</form>
{% endblock %}